apiVersion: v1
kind: Namespace
metadata:
  name: pagina

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pagina-nfspv
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.2.5
    path: "/home/pagina"
  

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pagina-nfspv
spec:
  storageClassName: storage-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---      

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagina-deployment
  namespace: pagina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagina
  template:
    metadata:
      labels:
        app: pagina
    spec:
      containers:
      - name: pagina
        image: 'wordpress'
        ports:
        - containerPort: 80
        volumeMounts:
          - name: volpagina
            mountPath: "/var/www/html"
      volumes:
      - name: volpagina
        persistentVolumeClaim:
          claimName: paginapvc001

---

apiVersion: v1
kind: Service
metadata:
  name: pagina-service
  namespace: pagina
spec:
  type: LoadBalancer
  selector:
    app: pagina
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32350
